### ISSUE TITLE
Enhance escrow interface for metadata resolution from escrowed NFTs & FT Vaults

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#112]
### Description

As reported by @bjartek, the interface for metadata resolution on escrowed NFTs is lacking. At a minimum a caller should be able to:
* Resolve a view against an escrowed NFT
* Get views supported by an escrowed NFT

Originally, the idea of exposing a reference to an escrowed resource sounded like a potential vulnerability given the ability to downcast the reference. However, any project implementing an NFT in a manner that would expose sensitive methods by downcasting form a publicly available reference (see [`ViewResolver.ResolverCollection.borrowViewResolver`](https://github.com/onflow/flow-nft/blob/master/contracts/ViewResolver.cdc#L50)) would be doing so against the intended use of the ecosystem standards and so would be vulnerable in any context, not exclusively from escrow.

What we'll likely do then is simply add the ability to borrow an escrowed NFT as a `&{ViewResolver.Resolver}` to `FlowEVMBridgeNFTEscrow` with a signature like:

```cadence
access(all) view fun borrowViewResolver(nftType: Type, id: UInt64): &{ViewResolver.Resolver}?
```

We'll of course also want to add a similar method to `FlowEVMBridgeTokenEscrow`

**Comment by bjartek** [comment]
we have https://github.com/onflow/flow-evm-bridge/blob/a9d52f9b715b141c343b985b1aafa7e25e3202f7/cadence/contracts/bridge/FlowEVMBridgeNFTEscrow.cdc#L124 so I am not sure this is really needed.

**Comment by sisyphusSmiling** [comment]
Updating to reflect recent conversations. Any non-view method calling through to an escrowed resource should be protected with `view` to ensure state in the escrowed resource cannot be mutated by external actors. To ensure metadata can be resolved, scripts should be updated to support retrieval of metadata solely within the context of a script which is inherently non-mutating.

**Comment by bluesign** [comment]
> Updating to reflect recent conversations. Any non-view method calling through to an escrowed resource should be protected with view to ensure state in the escrowed resource cannot be mutated by external actors. 

Seems you are trying to solve the unsolvable.
