### ISSUE TITLE
If the `storage.used` increasing during the withdraw, the bridging transaction will be broken.

### ISSUE THREAD

**Issue by btspoony** [onflow/flow-evm-bridge#125]
## Instructions

Bridge a NFT or FT which storage.used will be increated during the withdrawal.

### Problem

The bridging to evm transaction will be in a error.

### Steps to Reproduce 

Transaction Sample: https://www.flowdiver.io/tx/0e84fe1f20b56b025647bf55135a38fdea40f371172128e2fc46d019c949b95f?tab=script

Panic line: https://github.com/onflow/flow-evm-bridge/blob/main/cadence/transactions/bridge/tokens/bridge_tokens_to_evm.cdc#L67

All Fixes FT will have a chance to add metadata to Vault during withdraw, so the `storage.used` will be increased.

### Acceptance Criteria

Not to panic

**Comment by sisyphusSmiling** [comment]
Thanks for reporting. Yeah, we'll need to cover underflow in this case though it's not clear how the fee will be estimated in this case. The bridge has to charge fees based on storage consumption so there's a chance that the transaction will revert on withdrawing the fee from the scoped provider. I'll look into this

**Comment by bluesign** [comment]
passing function for fee is one option. something like:

```
self.coa.depositTokens(
            vault: <-self.sentVault,
            feeProviderFunc: fun(amount: UFix64):@{FungibleToken.Vault}{
            //here you can assert fee and decide to bridge or not 
           ....
            }
)
```
