### ISSUE TITLE
When using port to transfer a bridged ERC20, if the amount reaches 9 digits(UFix64 Integer part), the contract will throw an error.

### ISSUE THREAD

**Issue by btspoony** [onflow/flow-evm-bridge#126]
### Problem

Successful TX: https://www.flowdiver.io/tx/5ef517c8cd715d1196a489c6d88b8aa0f0b589059635b5fdf5d39c4e786fd6a9
Failed TX: https://www.flowdiver.io/tx/0c36b6d852d93698897e1755ca5c49067b1df7e81cf146565e4ee61dd2e49b09

### Steps to Reproduce 

The only differency is `amount`

### Acceptance Criteria

Not to panic

**Comment by sisyphusSmiling** [comment]
Closing as the failed transaction failed in the COA call to the ERC20 contract and doesn't involve bridge functionality.
