### ISSUE TITLE
Add support for onboard + bridge where possible

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#43]
### Issue To Be Solved
The need to onboard in a distinct transaction creates UX friction and we would like to alleviate this friction where possible. The limitation when bridging from EVM to Cadence is one related to the availability of deployed contract. A Cadence contract is not available in the runtime until after the deployment transaction has been executed. In order to bridge an asset from EVM to Cadence, a defining bridge-owned contract must exist in the runtime from which a corresponding asset can be minted. However, since the defining contract isn't available until after the deploying transaction, the deployment and bridge transaction must then be separate, thus breaking the atomicity of the desired transaction.

### Suggest A Solution
Explore if this limitation also exists for the EVM -> Cadence bridging path. If it does not, add support for onboard + bridge transactions along with test cases.
  
### Context
Aligns with ongoing wallet product work
cc @JeffreyDoyle @lmcmz

**Comment by bluesign** [comment]
>  A Cadence contract is not available in the runtime until after the deployment transaction has been executed. 

There can be few workarounds for that, such as you can mint and send on init etc. I will check bridge template contract, but should not be so hard.

**Comment by sisyphusSmiling** [comment]
Ah interesting idea @bluesign!
