### ISSUE TITLE
Transfer Transaction: Cadence -> EVM

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-evm-bridge#85]
### Issue To Be Solved
Transaction that allows transferring Fungible token from Cadence to EVM address.

Requirement for flow port to allow the user to transfer their Fungible / NFT from cadence to evm address

**Comment by sisyphusSmiling** [comment]
To clarify here, would the following interface work for your needs on this @bthaile?

```cadence
/// Bridges a Cadence fungible token from the signer's storage to the named recipient.
///
/// NOTE: This transaction also onboards the Vault to the bridge if necessary which may incur additional fees
///     than bridging an asset that has already been onboarded.
///
/// @param tokenContractAddress: The Flow account address hosting the FT-defining Cadence contract
/// @param tokenContractName: The name of the Vault-defining Cadence contract
/// @param amount: The amount of tokens to bridge from EVM
/// @param recipient: The hex address of the EVM recipient
///
transaction(tokenContractAddress: Address, tokenContractName: String, amount: UFix64, recipient: String)
```

Also wondering if it's safe to assume that the signer has sufficient funds in their Cadence Vault or if the transaction should consolidate balances across VMs to achieve the specified amount sent to the recipient.

**Comment by bthaile** [comment]
closing, looks like there is existing tx
